### ISSUE TITLE
Config files in subdirectories should inherit from and override the root config

### ISSUE THREAD

**Issue by jawshooah** [brigade/overcommit#139]
Overcommit should allow `.overcommit.yml` files in subdirectories to override settings in the root config for files in that subdirectory and its children, similar to [RuboCop](https://github.com/bbatsov/rubocop#inheritance).

For example, say I'm using the `Scalastyle` hook, but I'd like to use different `scalastyle-config.xml` files for application and test code. In the root `.overcommit.yml`, I would have

```yaml
Pre-Commit:
  Scalastyle:
    args: ['--config', 'scalastyle-config.xml']
```

And in my `test` directory:

```yaml
inherit_from: ../.overcommit.yml

Pre-Commit:
  Scalastyle:
    args: ['--config', 'test/scalastyle-config.xml']
```

**Comment by sds** [comment]
I'm hesitant to introduce this because my past experience has indicated this kind of configuration inheritance scheme is usually "Over"kill. (ha) It's annoying to have to consult multiple files in order to understand what configuration applies to a particular file (especially for complex inheritance chains). There is a significant benefit to having to consult a single file for all configuration.

For example, I would rather the tool in question support different configurations based on the paths involved, rather than Overcommit. I think this starts to tie yourself a little too tightly to Overcommit. Why not keep this in the realm of the tool itself?

Right now, you can hack your way around this by writing a custom hook that inherits from the other hook, and then using a different configuration, e.g.:

```ruby
module Overcommit::Hook::PreCommit
  class ScalastyleTest < Scalastyle; end
end
```

```yaml
PreCommit:
  Scalastyle:
    flags: ['--config', 'scalastyle-config.xml']
    exclude: 'test/**/*'

  ScalastyleTest:
    required_executable: 'scalastyle'
    flags: ['--config', 'test/scalastyle-config.xml']
    include: 'test/**/*.scala'
```

Definitely not as clean, I'll admit.

Another option is to add support for defining hooks declaratively (i.e. entirely within `.overcommit.yml`) and then support some sort of `inherit` option which allows you to copy the configurations/implementations of individual hooks and tweak them for a special case, e.g. 

```yaml
PreCommit:
  ScalastyleTest:
    inherit: 'Scalastyle'
    flags: ['--config', 'test/scalastyle-config.xml']
    include: 'test/**/*'
```

To reiterate: both of my proposed alternatives try to keep everything in one `.overcommit.yml`, rather than spreading out your configuration all over your repository. Does that make sense?
