### ISSUE TITLE
Add pre-commit hook to enforce file mode permissions

### ISSUE THREAD

**Issue by sds** [brigade/overcommit#191]
It's common when working in a collaborative environment to have individuals who have not configured their editors to save files with appropriate default file permissions. Usually this manifests itself as source files being committed that have unnecessary execute permissions.

It would be nice to have a `FileMode` pre-commit hook that allows you to enforce certain permissions for files matching specified glob patterns, e.g.

```yaml
PreCommit:
  FileMode:
    enabled: true
    mode:
      0644: '**/*rb'
      0755: 'bin/*'
```

Some unknowns here are how to deal with overlapping globs (is the first match the one that is enforced?), and how this plays out on Windows (which IIRC all files are executable). Leaving this here for comments.
