### ISSUE TITLE
Pre Push Hook is not running all hooks

### ISSUE THREAD

**Issue by pratik60** [brigade/overcommit#195]
Hi, for some reason custom hooks aren't running in PrePush hooks? Anyone can point me in the right direction
```
PrePush:
  ProtectedBranches:
    enabled: true
    description: 'Checking for illegal pushes to protected branches'
    branches: ['master']
  Jasmine:
    enabled: true
    description: 'Run suite of jasmine test cases'
    command: ['bundle', 'exec', 'rake', 'jasmine:ci']
  RSpec:
    enabled: true
    description: 'Running RSpec test suite'
    required_executable: 'rspec'
```

When you do a git push

```
Running pre-push hooks
Checking for illegal pushes to protected branches.[ProtectedBranches] OK
Running RSpec test suite......................................[RSpec] OK

✓ All pre-push hooks passed
```

It just ignores the jasmine test cases?
