### ISSUE TITLE
Allow hooks to be defined without accompanying Ruby code

### ISSUE THREAD

**Issue by sds** [brigade/overcommit#196]
It would be nice to be able to create a hook specifying nothing but a `command` without having to write any actual code. For repo-specific hooks where fancy per-line extraction via `extract_messages` isn't necessary, it would be convenient to just write something like:

```yaml
PrePush:
  Jasmine:
    enabled: true
    description: 'Run Jasmine test suite'
    command: ['bundle', 'exec', 'rake', 'jasmine:ci']
```

...in your `.overcommit.yml` file and have it _Just Work_™. The default behavior treats an exit status of zero as a pass, otherwise it's an error. I don't think we need to provide any additional options, e.g. mapping exit codes to `pass`, `warn`, or `fail` statuses, as the moment you need more complex logic you should be writing some code.

This lowers the barrier to entry for adding hook integrations with third-party tools.
