### ISSUE TITLE
EsLint hook ignores command option in config

### ISSUE THREAD

**Issue by derekpeterson** [brigade/overcommit#211]
We have Overcommit set-up in a Gem repo, and I'm trying to switch from JsHint to EsLint. In order to keep the project self-contained, I'm installing ESLint locally rather than globally. This means that running it involves using `./node_modules/.bin/eslint` rather than relying on the global `eslint`. I also want to lint only the JavaScript files being distributed with the gem. So, I have the following in `.overcommit.yml`:

```yaml
EsLint:
  enabled: true
  on_warn: pass
  command: ['./node_modules/.bin/eslint', 'gem/app/assets/javascripts']
```

I would expect Overcommit to use this command to run the ESLint pre-commit hook and to see the same results as when I run ESLint manually. What I see instead, though, is:

```shell
Analyzing with ESLint........................................[EsLint] FAILED
'eslint' is not installed (or is not in your PATH)
Install it by running: npm install -g eslint
```

That it's complaining about a missing global `eslint` on the path indicates that it's not using the command that I specified. I've read through the documentation a few times and looked at the hook code, but I can't figure out what I'm missing.

**Comment by derekpeterson** [comment]
Wait, I get what's happening: Overcommit is looking for `eslint` as the `required_executable` and failing because it's not on the path. Shouldn't that be unset if the user is specifying the `command`? It feels weird to have to include `required_executable: ''` in the config block.

**Comment by sds** [comment]
Hey @derekpeterson,

You need to set the `required_executable` option instead, as that is used when constructing the `command`. You can then specify 

```yaml
EsLint:
  enabled: true
  on_warn: pass
  required_executable: './node_modules/.bin/eslint'
  command: ['./node_modules/.bin/eslint', 'gem/app/assets/javascripts']
```

I'm not sure why you're modifying the `command` to explicitly pass `gem/app/assets/javascripts`. You can simply specify that path via the `include` option to only lint files in that directory.

I admit the `required_executable` behavior is a bit strange. We'll need to think on how to make this more intuitive.

**Comment by derekpeterson** [comment]
Oh, that makes way more sense. I've updated the config to this:

```yaml
EsLint:
  enabled: true
  on_warn: pass
  required_executable: './node_modules/.bin/eslint'
  include: 'gem/app/assets/javascripts'
```

Unfortunately, the ESLint hook doesn't run at all now.

**Comment by derekpeterson** [comment]
Never mind again. I had to pass a glob pattern to `include` to make it work: `'gem/app/assets/javascripts/**/*.js'` did the trick.

**Comment by jawshooah** [comment]
@sds What about the `Rubocop` and `TravisLint` configs in `.overcommit.yml`? They modify `command` directly without modifying `required_executable`:

```yaml
Rubocop:
  enabled: true
  command: ['bundle', 'exec', 'rubocop']

TravisLint:
  enabled: true
  command: ['bundle', 'exec', 'travis']
  flags: ['lint', '--skip-version
```

Is this because the `required_executable` for each hook should already be in the path, by virtue of being listed as dependencies in the gemspec?
