### ISSUE TITLE
Using rubocop with -a option.

### ISSUE THREAD

**Issue by skywinder** [brigade/overcommit#214]
I try to use rubocop with `-a` (`--auto-correct`) option to fix all minor issues automatically.

I try to put in the `.overcommit.yml` file strings like 

```
PreCommit:
  RuboCop:
    enabled: true
    command: ['rubocop', '-a'] 
    #or this:
    #command: ['bundle', 'exec', 'rubocop', '-a'] 
    on_warn: fail # Treat all warnings as failures
```

But it's not apply fixes to files before commit.

So, questions is: 
How to run `rubocop -a` before pre-commit checks automatically? Is there any option for it in overcommit project?
