### ISSUE TITLE
ScssLint is ignoring config file

### ISSUE THREAD

**Issue by croogie** [brigade/overcommit#239]
As in the title. Even if I put configuration like this:

```
PreCommit:
  ScssLint:
    enabled: true
    flags: ['-c', '.scss-lint.yml']
```

and there I will disable some linting rules - they are still working as run with default configuration.

Configuration is correct cause when I'm running command manually linting works as expected.
