### ISSUE TITLE
Support for CircleCI?

### ISSUE THREAD

**Issue by ericgross** [brigade/overcommit#248]
What is required in order to make this a reality?

**Comment by jawshooah** [comment]
Could you provide some more detail? Do you want to run Overcommit hooks as part of your CI process?

If so, why not just add `overcommit --run` to your `circle.yml`?

**Comment by wli** [comment]
Default config has a problem with AuthorEmail and AuthorName.

````
Checking author email...................................[AuthorEmail] FAILED
Author has an invalid email address: ''
Set your email with `git config --global user.email your_email@example.com`
Checking for author name.................................[AuthorName] FAILED
Author must have at least first and last name, but was: .
Set your name with `git config --global user.name "Your Name"`
````

Using this as the config:
````
# circle.yml
test:
  post:
    - bundle exec overcommit --run
````

To fix this, I did:
````
  # .overcommit.yml
  # Not required due to circle not having credentials
  AuthorEmail:
    enabled: true
    required: false

  # Not required due to circle not having credentials
  AuthorName:
    enabled: true
    required: false
````
and 
````
# circle.yml
test:
  post:
    - SKIP=AuthorEmail,AuthorName bundle exec overcommit --run
````
