### ISSUE TITLE
Standard fail/warn behavior?

### ISSUE THREAD

**Issue by JacobEvelyn** [brigade/overcommit#253]
I'm trying to standardize all of our linters so that anything on a modified line is a failure but anything on a non-modified line in the file is just a warning. However, I can't, for instance, seem to get some linters (like `haml-lint` and `scss-lint`) to give anything but warnings. Am I missing something?

I tried this, with no luck:

```yaml
PreCommit:
  All:
    problem_on_unmodified_line: warn
    on_warn: fail
```

**Comment by sds** [comment]
Hey @JacobEvelyn,

Not sure if this is was just a copy/paste error, but `All` should be capitalized to `ALL` in your example. Does changing that solve the issue?

**Comment by JacobEvelyn** [comment]
Ah, good catch, thanks! Changing that *changes* the issue but doesn't solve it; now (as I suspected might happen), all linter complaints on non-modified errors are treated as failures because of the `on_warn: fail` rule, when I want them to be warnings.

To clarify, my desired behavior is something like this:

```yaml
PreCommit:
  ALL:
    problem_on_unmodified_line: warn
    problem_on_modified_line: fail
```

Is there any way to achieve this?
