### ISSUE TITLE
ProtectedBranches not protective

### ISSUE THREAD

**Issue by ainth** [brigade/overcommit#271]
Given the following `.overcommit.yml`:
```
PrePush:
  ProtectedBranches:
    enabled: true
    description: 'Check for force push to protected branch'
    branches: ['master', 'release', 'integration']
```
When I am on `master` and am 1 commit behind `origin/master` and I make some changes and run:
`git add -A`
`git commit -m "somechanges"`
`git push -f`
Then I see:
```
➜  push-control-test git:(master) git push -f
Running pre-push hooks
Check for force push to protected branch..........[ProtectedBranches] OK

✓ All pre-push hooks passed

```
And the master branch is ruined :(
