### ISSUE TITLE
Parallel tests

### ISSUE THREAD

**Issue by pratik60** [brigade/overcommit#273]
Quick Question

If I wish to run parallel tests, is this enough in overcommit.yml?

```
PrePush:
  RSpec:
    enabled: true
    description: 'Running RSpec test suite'
    required_executable: 'rspec'
    command: ['bundle', 'exec', 'rake', 'parallel:spec']
```

I don't think parallel test is running....Also worried cause it didn't ask for signature verification
