### ISSUE TITLE
HardTabs should omit Makefiles

### ISSUE THREAD

**Issue by dividedmind** [brigade/overcommit#276]
Makefiles need to have hard tabs in them.

**Comment by sds** [comment]
Hey @dividedmind,

Overcommit used to add special cases for a number of different file types, but this quickly got out of hand and unrealistic for this project to manage.

Instead, we encourage developers to add exclusions as they see fit. You can easily exclude Makefiles from the `HardTabs` hook by adding the following to your `.overcommit.yml`:

```yaml
PreCommit:
  HardTabs:
    exclude:
      - '**/Makefile'
```

Hope that helps.
