### ISSUE TITLE
Excluding files not working properly

### ISSUE THREAD

**Issue by MaximilianoFelice** [brigade/overcommit#297]
Hi! We've been trying Overcommit in one of our latest projects at work, and after a few weeks of development, we noticed that some of the excluded files and directories are still being analyzed.

My current configuration for a Rails project consists on:

```yml
PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['bundle', 'exec', 'rubocop']
  JsHint:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['bundle', 'exec', 'rake', 'jshint']
    flags: []
    exclude:
      - "vendor/**/*.js"
  CssLint:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['bundle', 'exec', 'rake', 'custom_css_lint:run']
    flags: []
    exclude:
      - 'app/assets/stylesheets/flat-dream.scss'
```

As you see, it's not much of a complicated configuration, but still excluded files and directories are analyzed and shown as errors. There are other file patterns we've used as well, but none of them work.

I've been trying to add some spec testing this bug with no apparent luck, as over the gem's testing environment both file and directory exclusion are working. I hope to come back here with a more complete report in a few days, but it would really help to know if some of you are experiencing any similar problems.

Thanks!
