### ISSUE TITLE
Add hint to hook options

### ISSUE THREAD

**Issue by senechaux** [brigade/overcommit#302]
It would be great to have an optional message in the hook configuration to show the user useful information if the hook failed, in example we could use the "hint" to show a command to fix the problem with the hook.

I could try to prepare a Pull Request if you want to.

**Comment by sds** [comment]
Hey @senechaux,

Hooks can already display output when something fails. This output can provide additional information about how to fix the problem.

With this in mind, I see no need to include a separate `hint` option.

**Comment by senechaux** [comment]
Hi @sds,

thank you for your response. I don't see any option in overcommit configuration for additional information so I think you mean the information provided by the executable (jshint, scss-lint, ...), right? If so I think it would be great to have an additional message in overcommit configuration like (check last line):
``` yaml
  ScssLint:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    description: 'Analyzing with scss-lint'
    required_executable: 'scss-lint'
    install_command: 'gem install scss_lint'
    include: '**/*.scss'
    hint: 'You can fix most errors with fixmyjs'
```

**Comment by sds** [comment]
Hey @senechaux,

My point is that a well-written hook should already tell you how to solve the problems it reports. Thus when writing a hook, when you extract the error messages from the external tool you can include your own message that tells you how to fix the problem.

I don't see the need to pollute the option space with a distinct option. If I'm missing something here, please provide an explicit use case (using a concrete hook as an example would be best&mdash;your example above makes no sense since the `ScssLint` hook does not have an auto-correction feature). Thanks!

**Comment by senechaux** [comment]
Hi @sds ,

I don't want to make this conversation too long because I think it depends on the point of view but here a real use case:
``` yaml
JsHint:
    enabled: false
    description: 'Analyzing with JSHint'
    required_executable: 'jshint'
    flags: ['--verbose']
    install_command: 'npm install -g jshint'
    include: '**/*.js'
    hint: 'You can fix most errors with fixmyjs https://github.com/jshint/fixmyjs'
```

Fixmyjs is a tool that can use the JsHint configuration to to automatically fix JavaScript errors in a non-destructive way.

I could create a custom hook to add this message so if you don't see this as a good reason it's ok for me.

Best regards,
