### ISSUE TITLE
Print to stdout for custom scripts

### ISSUE THREAD

**Issue by hasghari** [brigade/overcommit#305]
I have configured my `.overcommit.yml` file to execute a custom script on post-commit:

```yml
PostCommit:
  CustomScript:
    enabled: true
    required_executable: './script/todo-postcommit.sh'
```

However, the output from the script is not printed to stdout. Is this a bug or intentional?
