### ISSUE TITLE
RailsBestPractices not running

### ISSUE THREAD

**Issue by cheerfulstoic** [brigade/overcommit#324]
My `.overcommit.yml`:

```yaml

PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

  TrailingWhitespace:
    enabled: true
    include:
      - '**/*.rb'
    exclude:
      - '**/db/structure.sql' # Ignore trailing whitespace in generated files

  LocalPathsInGemfile:
    enabled: true

  RailsBestPractices:
    enabled: true
    quiet: false

  # CoffeeLint:
  #   enabled: true
```

Output:

```
$ overcommit -r
Running pre-commit hooks
Checking for local paths in Gemfile.............[LocalPathsInGemfile] OK
Analyzing with RuboCop......................................[RuboCop] FAILED
Errors on modified lines:
/Users/brian/github/northwoodspd/traverse/app/helpers/home_helper.rb:2:1: C: Style/TrailingWhitespace: Trailing whitespace detected.

Checking for trailing whitespace.................[TrailingWhitespace] FAILED
Errors on modified lines:
/Users/brian/github/northwoodspd/traverse/app/helpers/home_helper.rb:2:


✗ One or more pre-commit hooks failed
```
