### ISSUE TITLE
specify exceptions for the ExecutePermissions hook

### ISSUE THREAD

**Issue by deepak** [brigade/overcommit#339]
configured `ExecutePermissions` as

```
  ExecutePermissions:
    enabled: true
```

it caught files with execute permission

but some files eg. under the bin folder need to have the execute permission
so it will be nice to add exceptions

and maybe the converse rule as well
eg. files under the bin folder need to have the execute permission

**Comment by sds** [comment]
You can exclude files using the [`exclude` hook option](https://github.com/brigade/overcommit#hook-options).

```yaml
  ExecutePermissions:
    enabled: true
    exclude: 
      - 'bin/**/*'
```
