### ISSUE TITLE
ScssLint not using config file

### ISSUE THREAD

**Issue by ericgross** [brigade/overcommit#351]
I have a .scss-lint.yml file that is being ignored by my PreCommit hook.

.scss-lint.yml:
`scss_files: 'app/assets/stylesheets/**/*.scss'`

.overcommit.yml:
```
PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
  Reek:
    enabled: true
  ScssLint:
    enabled: true
PrePush:
  RSpec:
    enabled: true

```

And the output has a ton of errors from files such as:
`/Users/eric/Development/proj/web/vendor/assets/stylesheets/bourbon/_bourbon.scss:72 StringQuotes: Prefer single quoted strings`
