### ISSUE TITLE
Execute hooks in subdirectories

### ISSUE THREAD

**Issue by muuki88** [brigade/overcommit#363]
Hi,

I would like to execute hooks on subdirectories, because we have two different applications in our project. Both npm/webpack based builds.

The configuration looks like this

```yml
  EsLint:
    enabled: true
    required_executable: 'npm'
    # Disable progress and colours for NPM as these break the hook on non-TTY
    # environments.  Also use compact format for eslint because overcommit
    # expects that to parse errors
    command: ['npm', '--no-progress', '--no-color', 'run', 'lint', '--', '--format=compact']
    install_command: ['npm', 'install']
    # Replicate eslintignore for committed files to avoid warnings from eslint
    # about checking ignored files files
    include: ['**/*.js', '**/*.jsx']
    exclude: ['webpack.config.*.js']
```

I would like to execute this hook in the `admin` and `frontend` folder. Is that possible?

Thanks,
Muki

**Comment by sds** [comment]
Hey Muki,

To my knowledge (though I'm not a user myself), `eslint` supports configuration based on the directory of the file being linted. So even if you run `eslint` at the root of your repository, it should still use the configuration specified in the `admin` and `frontend` directories for files in those respective directories.

Thus you should be able to change the `EsLint` hook's `include` option to:

```yaml
EsLint:
  include: 
    - 'admin/**/*.js'
    - 'frontend/**/*.js'
```

...so that it only executes on those files. 

If my understanding of `eslint`'s behavior is incorrect, or I'm misunderstanding your question, let me know.
