### ISSUE TITLE
Eslint doesn't run on git commit but does with overcommit -r

### ISSUE THREAD

**Issue by saadshahd** [brigade/overcommit#370]
Eslint doesn't run on `git commit` but does with `overcommit -r`

**git commit**
```
» git commit
Running pre-commit hooks

✓ All pre-commit hooks passed
```

**overcommit -r**
```
» overcommit -r
Running pre-commit hooks
Analyze with ESLint..........................................[EsLint] FAILED
Errors on modified lines:
webapp/app/scripts/services/api.js: line 14, col 5, Error - Block must not be padded by blank lines. (padded-blocks)

✗ One or more pre-commit hooks failed

```

**.overcommit.yml**
```
verify_signatures: false

PreCommit:
  EsLint:
    enabled: true
    command: ['eslint', 'app/scripts']
    flags: ['--fix', '--format=compact']
    include:
      - '.eslintrc'

CommitMsg:
  SpellCheck:
    enabled: true

PrePush:
  ProtectedBranches:
    enabled: true
    branches: ['master', 'dev']

  JsHint:
    enabled: true
    command: ['jshint', 'test/spec']
    flags: ['--verbose']
    include:
      - 'test/.jshintrc'
```
