### ISSUE TITLE
EsLint precommit hook not working

### ISSUE THREAD

**Issue by jason-feng** [brigade/overcommit#371]
I have EsLint installed locally, however it is not being triggered by overcommit

Below is a copy of my .overcommit.yml

```
PreCommit:
  EsLint:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    required_executable: './node_modules/.bin/eslint'
    command: './node_modules/.bin/eslint'
```

This is the output of overcommit when I run it

```
Running pre-commit hooks

✓ All pre-commit hooks passed
```

It seems like it doesn't even run EsLint, but also no errors are thrown. Not sure what the problem is, all help would be appreciated
