### ISSUE TITLE
Is it possible to wait until push to run the CommitMsg hook?

### ISSUE THREAD

**Issue by monfresh** [brigade/overcommit#389]
A typical workflow when working on a branch is to make several commits locally without pushing to GitHub, and once it's ready to be pushed as a pull request, the commits might or might not be squashed. Having overcommit complain about each individual commit interrupts the flow. It would be a much better experience to wait until the commits are actually pushed before checking them.

Is there a way to configure this behavior?

Thanks!

**Comment by sds** [comment]
Hey @monfresh,

`CommitMsg` hooks aren't triggered by Overcommit, but by `git` itself.

Your potential options/workarounds are:

- Move your `CommitMsg` hooks to `PrePush` hooks so they only run on push
- Disable `CommitMsg` hooks entirely

At the end of the day, creating a `CommitMsg` hook indicates you want the hook to run when `git` runs the `commit-msg` hook. There's no getting around this other than to move your checks into a different hook.

Hope this helps!

**Comment by monfresh** [comment]
Thanks! How do I move my `CommitMsg` hooks to `PrePush`? I tried both of these, and neither worked:
```
PrePush:
  CapitalizedSubject:
    enabled: true
    description: 'Check subject capitalization'
```
```
PrePush:
  CommitMsg:
    CapitalizedSubject:
      enabled: true
      description: 'Check subject capitalization'
```
