### ISSUE TITLE
How to change directories?

### ISSUE THREAD

**Issue by fingermark** [brigade/overcommit#390]
I'm trying to create a pre-commit hook that runs `npm run lint`, but my package.json and files to lint on are in a directory a few paths deep.

Is there a way to cd to a directory (./path/to/directory) before running this:

```
PreCommit:
  EsLint:
    enabled: true
    command: ['npm', 'run', 'lint]
    on_warn: fail
    quiet: false
    required_executable: './path/to/directory/node_modules/.bin/eslint'
    flags: ['--format=compact']
    install_command: 'npm install'
```

If not, I tried creating a script in that `./path/to/directory` called `lint.sh`:

```
cd "$(dirname "$0")"
EXIT_CODE=${npm run lint}
echo "code: $EXIT_CODE"
exit $EXIT_CODE
```

It seems to always pass no matter what the exit code is and I can't confirm it's actually executing that code.

**Comment by jawshooah** [comment]
Try adding this to `.git-hooks/pre_commit` and name it `custom_es_lint.rb`:

```ruby
module Overcommit::Hook::PreCommit
  class CustomEsLint < EsLint
    def run
      FileUtils.cd 'path/to/directory' do
        super()
      end
    end
  end
end
```

Then configure it in `.overcommit.yml` as follows:

```yaml
PreCommit:
  CustomEsLint:
    enabled: true
    on_warn: fail
    required_executable: 'npm'
    command: ['npm', 'run', 'lint']
    flags: ['--', '--format=compact']
```

**Comment by sds** [comment]
Note that changing the directly within a hook is dangerous if your hooks are running in parallel (the default as of Overcommit 0.32.0). Since the current directory is changed for the entire process, other hooks can be affected by the change, resulting in unexpected output!

To avoid this, you'll need to set `parallelize: false` on the hook to ensure it is the only hook running during its execution.

**Comment by deanius** [comment]
Isn't the question of Overcommit ignoring the exit code still an issue? I've lost time on this - it really doesn't seem to pick up an exit code of a `command` - is turning it into a custom ruby class necessary? I'm confused how a non-zero-exit code gets lost when that's the reason this tool exists.

```
  Prettier:
    enabled: true
    quiet: false
    required_executable: './node_modules/.bin/prettier'
    command: ['./node_modules/.bin/prettier', '-c', '/tmp/FILENOTFOUND.js']
    description: 'Ensure Prettier is used to format JS'
```

```
Ensure Prettier is used to format JS.......................[Prettier] OK

✓ All pre-commit hooks passed
```
