### ISSUE TITLE
Overcommit should error when environment variables are not strings

### ISSUE THREAD

**Issue by binarymason** [brigade/overcommit#423]
#### When env variable value is a boolean...
```yml
PrePush:
  RSpec:
    enabled: true
    quiet: false
    description: 'Run RSpec test suite'
    env:
      CODE_COVERAGE: true
    command: ['bundle', 'exec', 'rspec', 'spec', '--tag', '~type:request']
```

#### Overcommit blows up.
```sh
$ git push
Running pre-push hooks
Run RSpec test suite..........................................[RSpec] FAILED
Hook raised unexpected error
no implicit conversion of true into String
```

#### When env variable is string...
```yml
PrePush:
  RSpec:
    enabled: true
    quiet: false
    description: 'Run RSpec test suite'
    env:
      CODE_COVERAGE: 'truthy' # why does this have to be a string?
    command: ['bundle', 'exec', 'rspec', 'spec', '--tag', '~type:request']
```

#### Overcommit works with no issues.

Am I missing something or does overcommit depend on having a string?
