### ISSUE TITLE
Using semistandard with --fix option <question>

### ISSUE THREAD

**Issue by getupandgo** [brigade/overcommit#426]
I want to run semistandard's code style fix procedure before each commit (so i can disregard trailing spaces errors and similar stuff). Can i achieve this behaviour now?

**Comment by sds** [comment]
Hey @getupandgo,

All pre-commit hooks support the `flags` option, allowing you to specify the list of flags passed to the command.

Looking at the [default configuration for Semistandard](https://github.com/brigade/overcommit/blob/v0.36.0/config/default.yml#L522-L528):

```yaml
  SemiStandard:
    enabled: false
    description: 'Analyze with semistandard'
    required_executable: 'semistandard'
    flags: ['--verbose']
    install_command: 'npm install -g semistandard'
    include: '**/*.js'
```

...you can easily add the `--fix` flag to the `flags` option. Therefore your `.overcommit.yml` will look like:

```yaml
PreCommit:
  SemiStandard:
    enabled: true
    flags: ['--verbose', '--fix']
```

This is documented in the [Hook Options section of the README](https://github.com/brigade/overcommit#hook-options).
