### ISSUE TITLE
Improve ad hoc hook warning about `required_executable`/`command` tracked by git

### ISSUE THREAD

**Issue by KamilLelonek** [brigade/overcommit#427]
My `.overcommit.yml` looks like:

```
PrePush:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    on_warn: fail

  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec']
    on_warn: fail

PostCheckout:
  BundleInstall:
    enabled: true
    on_warn: fail
```

And when I try to `git push` I get a message:

```
Hook must specify a `required_executable` or `command` that is tracked by git (i.e. is a path relative to the root of the repository) so that it can be signed
```

What should I do in such case?
