### ISSUE TITLE
TrailingWhitespace does not work as PreCommit

### ISSUE THREAD

**Issue by jclif** [brigade/overcommit#431]
I have tried adding TrailingWhitespace to my PreCommit, but it does not work when I try to commit files. Interestingly, it still works when I run `overcommit -r`. Has anyone else encountered this issue?

Additionally, I'm seeing the Rubocop check fail when I run `overcommit -r`, but pass when I commit.

**Comment by sds** [comment]
Hey @jclif,

Remember that you must stage the changes to those files with `git add ...` in order for them to be checked as part of the pre-commit hook run. `overcommit --run` doesn't care which changes were staged&mdash;it only cares that the files are tracked by Git.

Also remember that you must explicitly enable the hook in your YAML configuration:

```yaml
PreCommit:
  TrailingWhitespace:
    enabled: true
```

I'm going to close this as this is the overwhelming reason why people see this behavior.

**Comment by jclif** [comment]
@sds Appreciate the quick response! I've ensured that all files are in staging, and that my `overcommit.yml` file is set up properly:
```
CommitMsg:
  RussianNovel:
    enabled: true

PreCommit:
  TrailingWhitespace:
    enabled: true

  RuboCop:
    enabled: true

  BundleAudit:
    enabled: true
```

I still appear to be encountering the same issues. I also noticed that commenting blocks in my `rubocop_todo.yml` produces more warnings when running `overcommit -r`, but not when commiting. Are there any other common issues to look out for?

**Comment by jclif** [comment]
@sds Thanks for the quick response! I have ensured that the file I expect to fail TrailingWhitepace is in staging, but it seems to pass just fine. Here is my `overcommit.yml` for reference:
```
CommitMsg:
  RussianNovel:
    enabled: true

PreCommit:
  TrailingWhitespace:
    enabled: true

  RuboCop:
    enabled: true

  BundleAudit:
    enabled: true
```

Actually, I'm now also noticing that the RussianNovel check is not running whenever I try to commit:
<img width="551" alt="screen shot 2016-09-16 at 5 18 14 pm" src="https://cloud.githubusercontent.com/assets/3463691/18601572/96af6212-7c31-11e6-8194-235fb4818122.png">
This is me canceling a commit with an empty message.
