### ISSUE TITLE
post-checkout hook on file checkout

### ISSUE THREAD

**Issue by rpereira** [brigade/overcommit#449]
Hello,

Is it possible to avoid running the post-checkout hook on a file checkout, so that we avoid the following output: 
```
$ git checkout -- my_file
Running post-checkout hooks
Installing missing dependencies.................[InstallDependencies] OK

✓ All post-checkout hooks passed
```

This is my config:

```
PostCheckout:
  InstallDependencies:
    description: 'Installing missing dependencies'
    enabled: true
    required_executable: './scripts/install_dependencies.sh'
```

I'm aware that is possible to exit the script if a file checkout happens by doing `[ "$3" = 0 ] && exit 0`, but ideally it would be possible to configure Overcommit to not run when a file checkout happens, hence avoiding the output above.

Thanks.
