### ISSUE TITLE
Adding cucumber to prepush

### ISSUE THREAD

**Issue by magicalbanana** [brigade/overcommit#469]
How do you add cucumber testing using `bundle exec` to pre-push? Here's my attempt

```yaml
  Cucumber:
    enabled: true
    on_warn: 'pass'
    required_executable: './script/cucumber'
    command: ['bundle', 'exec', 'cucumber']
```

But I keep getting this error:

```sh
/Users/kgan/.gem/ruby/2.3.3/gems/overcommit-0.37.0/lib/overcommit/hook_signer.rb:39:in `hook_path': Hook must specify a `required_executable` or `command` that is tracked by git (i.e. is a path relative to the root of the repository) so that it can be signed (Overcommit::Exceptions::InvalidHookDefinition)
```
