### ISSUE TITLE
Pre-commit hooks seem slow

### ISSUE THREAD

**Issue by AlexEvanczuk** [brigade/overcommit#471]
Hello --
I just discovered this library as I was working on a similar project as a side-project at work, and pretty excited about this.  I'm running into some issues though where the hooks seem like they're running quite slowly.  Even when I have all of my hooks disabled, I am getting speeds around ~5-6 seconds per commit:

```
alex.evanczuk@us-aevanczuk (add_overcommit_for_commit_hooks !) $ time git commit -am 'testing overcommit speed'
Running pre-commit hooks

✓ All pre-commit hooks passed

[add_overcommit_for_commit_hooks a330e6] testing overcommit speed
 1 file changed, 10 insertions(+), 10 deletions(-)

real	0m5.611s
user	0m2.097s
sys	0m7.043s
```

When I run with a change in a single .rb file and my other hooks enabled (but skipped because there is no applicable file), it is taking roughly 14 seconds:
```
real	0m13.822s
user	0m4.895s
sys	0m9.903s
```

My `overcommit.yml` is below.  Is this the base startup time that is to be expected always?  Is there a way to speed things up or is this to be expected with the ruby startup time?

```
gemfile: false

verify_signatures: false

# Hooks that are run after `git commit` is executed, before the commit message
# editor is displayed. These hooks are ideal for syntax checkers, linters, and
# other checks that you want to run before you allow a commit object to be
PreCommit:
  ALL:
    parallelize: true
    requires_files: true

  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    flags: ['--force-exclusion', '--display-cop-names', '--config=.rubocop.yml']
    install_command: 'gem install rubocop'
    required_executable: 'rubocop'
    include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.rb'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

  CoffeeLint:
    enabled: true
    required_executable: 'coffeelint'
    flags: ['-f=coffeelint.json']
    install_command: 'yarn add coffeelint'
    include: '**/*.coffee'

  EsLint:
    enabled: true
    required_executable: 'eslint'
    flags: ['--config=.eslintrc']
    install_command: 'yarn add eslint'
    command: ['node_modules/.bin/eslint']
    include:
      - app/assets/javascripts/**/*.jsx
      - app/assets/javascripts/**/*.js
      - spec/javascripts/**/*.jsx
      - spec/javascripts/**/*.js
      - frontend/javascripts/**/*.jsx
      - frontend/javascripts/**/*.js
      - koala/app/assets/javascripts/**/*.jsx
      - koala/app/assets/javascripts/**/*.js

  ScssLint:
    enabled: true
    required_library: 'json'
    required_executable: 'scss-lint'
    flags: ['--config=.scss-lint.yml']
    install_command: 'gem install scss_lint'
    include: '**/*.scss'

  MergeConflicts:
    enabled: true
    quiet: true
    required_executable: 'grep'
    flags: ['-IHn', "^<<<<<<<[ \t]"]

  RailsSchemaUpToDate:
    enabled: true
    include:
      - 'db/migrate/*.rb'
      - 'db/schema.rb'
      - 'db/structure.sql'

  AuthorName:
    enabled: false

  AuthorEmail:
    enabled: false

  BrokenSymlinks:
    enabled: false

# Hooks that are run against every commit message after a user has written it.
# These hooks are useful for enforcing policies on commit messages written for a
# project.
CommitMsg:
  CapitalizedSubject:
    enabled: false
  EmptyMessage:
    enabled: false
  SingleLineSubject:
    enabled: false
  TextWidth:
    enabled: false
  TrailingPeriod:
    enabled: false

# Hooks that run after HEAD changes or a file is explicitly checked out.
PostCheckout:

# Hooks that run after a commit is created.
PostCommit:

# Hooks that run after `git merge` executes successfully (no merge conflicts).
PostMerge:

# Hooks that run after a commit is modified by an amend or rebase.
PostRewrite:

# Hooks that run during `git push`, after remote refs have been updated but
# before any objects have been transferred.
PrePush:
```

**Comment by trotzig** [comment]
I don't have a lot of context on how overcommit will perform in different scenarios. We're at 5-6 seconds too, but that's with a lot more checks than what you have. It would be interesting to see if you get the same performance on a fresh new project with all checks disabled.

**Comment by sds** [comment]
Hey @AlexEvanczuk,

Normally slow hook times are caused by the initial startup delay due to Bundler resolving your gem dependency graph. However, since you have `gemfile: false` in your `.overcommit.yml`, this shouldn't be the case.

FWIW, running pre-commit hooks for an empty commit on a project on my local machine takes ~1.5s. It sounds like there is something suspicious with your machine that is unrelated to Overcommit.

If you have some time, we would really appreciate if you did some profiling on your local machine to see what's going on. I have seen issues on systems running virus scanning or similar software which log system calls made by programs, as this will significantly slow down execution.

Thanks for your help!

**Comment by sds** [comment]
Closing due to lack of response. Feel free to reopen with additional information that helps shed light on the issue!

**Comment by jasantunes** [comment]
I'm experiencing the same slowness, even without performing any checks.

```
# .overcommit.yml
CommitMsg:
  ALL:
    enabled: false
PreCommit:
  ALL:
    enabled: false
```

Running `git commit` w/ overcommit (w/o any checks) takes ~1.5 sec:
```
$ touch t.txt && git add t.txt && time git commit -m "empty commit"
[master 652f3f6634] empty commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 t.txt
git commit -m "empty commit"  1.53s user 1.25s system 57% cpu 4.856 total

$ git reset --hard HEAD~1
HEAD is now at cc1bc92cbe empty commit

$ overcommit --uninstall
Removing hooks from /Users/joao/dev/reputedly
Successfully removed hooks from /Users/joao/dev/reputedly

$ touch t.txt && git add t.txt && time git commit -m "empty commit"
[master 3ad796c0a1] empty commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 t.txt
git commit -m "empty commit"  0.01s user 0.03s system 140% cpu 0.033 total
```
Is there a way to speed up overcommit loading time?
