### ISSUE TITLE
Freeze when parallelize is disabled for a hook

### ISSUE THREAD

**Issue by detouched** [brigade/overcommit#476]
I created a custom hook which requires `parallelize: false`, but Overcommit apparently hangs with such setup.

It turned out that even with only bundled plugins it behaves the same.

Steps to reproduce:
* Configure the following `.overcommit.yml`:
```
CommitMsg:
  TrailingPeriod:
    enabled: true
    parallelize: false
```
* Try `git commit -m "Test"`. You'll see something like
```
$ git commit -m "Test"
Running pre-commit hooks

✓ All pre-commit hooks passed

Running commit-msg hooks
Check for trailing periods in subject................[TrailingPeriod] OK
```
This will never proceed until you interrupt it with Ctrl+C.
