### ISSUE TITLE
Overcommit pre-push hooks freeze between tasks

### ISSUE THREAD

**Issue by klintzz** [brigade/overcommit#478]
Hi, I've had this issue with overcommit for a while where my pre-push rake tasks freeze between tasks.  I've been getting around this by coding a monolithic pre-push hook, but recently while refactoring I checked again and and decided to post an issue.   Any help or feedback would be greatly appreciated!

After the first test completes, it prints the result of the first test, then locks up:

```
➜   git:(dummy_data) git push origin dummy_data
Running pre-push hooks
Making sure commit passes paperclip tests.............[Papercliptest] OK
^C

➜   git:(dummy_data) ✗ Interrupt signal received. Stopping hooks...

⚠  Hook run interrupted by user

```

I saw a similar issue and tried to trace the process a bit:
```
89842/0x309431:  ioctl(0x1, 0x4004667A, 0x7FFF579FA2DC)          = -1 Err#25
89842/0x309431:  ioctl(0x1, 0x40487413, 0x7FFF579FA2E0)          = -1 Err#25
89842/0x309431:  sigprocmask(0x0, 0x0, 0x0)              = 0x0 0
dtrace: 1023 dynamic variable drops with non-empty dirty list
89814/0x30942f:  poll(0x700002851EB0, 0x2, 0xFFFFFFFF)           = 1 0
dtrace: error on enabled probe ID 2315 (ID 901: syscall::thread_selfid:return): invalid user access in action #5 at DIF offset 0
```

The code that locks is as follows:

`overcommit.yml`
```
PrePush:
  Papercliptest:
    enabled: true
    description: "Making sure commit passes paperclip tests"
    quiet: false
    env: 
      PAPERCLIP_TEST: "1"
    command: ['bundle','exec', 'rake', 'pre_push:paperclip_tests']
    branches: ['master', 'development', 'dummy_data']
  Servicestest:
    enabled: true
    quiet: false
    description: "Making sure commit passes services tests"
    command: ['bundle','exec', 'rake', 'pre_push:services_tests']
    branches: ['master', 'development', 'dummy_data']
  Integrationtest:
    enabled: true
    quiet: false
    description: "Making sure commit passes integration tests"
    command: ['bundle','exec', 'rake', 'pre_push:integration_tests']
    branches: ['master', 'development', 'dummy_data']
    parallelize: false
```

`lib/tasks/pre_push.rake`

```
namespace :pre_push do |pp|

  desc "runs integration tests"
  Rake::TestTask.new(:integration_tests) do |t|
    t.libs << "test"
    t.test_files = FileList['test/integration/*.rb']
    t.verbose = true
    # throws some bizarre circular depency error because of the require
    t.warning = false
  end

  desc "runs paperclip tests"
  Rake::TestTask.new(:paperclip_tests) do |t|
    t.libs << "test"
    t.test_files = FileList['test/paperclip/*.rb']
    t.verbose = true
    t.warning = false
  end

  desc "runs services tests"
  Rake::TestTask.new(:services_tests) do |t|
    t.libs << "test"
    t.test_files = FileList['test/services/*.rb']
    t.verbose = true
    t.warning = false
  end
end
```

`papercliptest.rb`
```
module Overcommit::Hook::PrePush
  class Papercliptest < Base

    attr_accessor :protected_push

    def run
      if protected_pushes.any?
        result = execute(config['command'])
        return :fail, "Paperclip Test failed when pushing to a protected branch:\n#{result.inspect}\n#{result.stdout}" unless result.success?
      end
      return :pass
    end


    #This code was hacked from https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_push/protected_branches.rb

    def protected_pushes
      @protected_pushes ||= pushed_refs.select do |pushed_ref|
        protected?(pushed_ref.remote_ref)
      end
    end

    def protected?(remote_ref)
      ref_name = remote_ref[%r{refs/heads/(.*)}, 1]
      protected_branch_patterns.any? do |pattern|
        File.fnmatch(pattern, ref_name)
      end
    end

    def protected_branch_patterns
      @protected_branch_patterns ||= Array(config['branches']).
      concat(Array(config['branch_patterns']))
    end

  end
end
```
