### ISSUE TITLE
haml-lint: Does not honor per-linter excludes from .haml-lint.yml

### ISSUE THREAD

**Issue by shaneog** [brigade/overcommit#483]
I am running haml-lint via overcommit.
When I set up the `.haml-lint.yml` file and run `haml-lint` manually, I have no lint offenses.
However, when I enable overcommit and/or run `overcommit --run` the  `exclude` is not honored.

If I change the `exclude` to `enabled: false` then the linter is correctly disabled.

```yaml
linters:
  ConsecutiveComments:
    exclude:
      - 'app/views/layouts/partials/_head_javascript.html.haml'

```

I am also receiving the error when overcommit `pre-commit` or `--run` is executed (haml-lint) specific:
> Unexpected output: unable to determine line number or type of error/warning for output:
> 1 file inspected, 1 lint detected
> ✗ One or more pre-commit hooks failed

Gems:
```
haml_lint (0.24.0)
overcommit (0.39.0)
```

**Comment by trotzig** [comment]
Hi @shaneog, let me see if I can help you out. 

First, is this the config that you expect to apply to haml_lint? 

```
linters:
  ConsecutiveComments:
    exclude:
      - 'app/views/layouts/partials/_head_javascript.html.haml'
```

It looks like it belongs to a custom check named "ConsecutiveComments". Which could explain why the excludes config is not working. I might be missing something though.

**Comment by shaneog** [comment]
Thanks @trotzig.

`ConsecutiveComments` is a linter provided [within haml-lint](https://github.com/brigade/haml-lint/blob/master/config/default.yml#L23).

I have made a minimum test case to reproduce the bug: https://github.com/shaneog/overcommit-haml-bug

There is a README file to explain everything there.

**Comment by trotzig** [comment]
Ah, of course! I'm one of the maintainers of haml-lint too, so I should have noticed the config not belonging to overcommit. 

Let me have a look at that repro case. Thanks for providing a way to reproduce!

**Comment by mbeasley** [comment]
If this is any help, there may be multiple issues going on. @shaneog I came across the same error that you showed in your bug repo and the problem I found was that haml-lint changed their default reporter to include the summary line: `1 file inspected, 1 lint detected` which overcommit can't parse.

I think maybe it would make sense for haml-lint to report summary info to STDERR and only the actual lines to STDOUT, **but** a work around in overcommit is to add `flags: --no-summary` to your overcommit configuration for haml-lint.

I don't know if that will have any effect on your other part of this issue, about overcommit respecting the haml-lint config.

**Comment by trotzig** [comment]
Adding the `--no-summary` flag does indeed help past the summary issue. This was something I was supposed to take care of after https://github.com/brigade/haml-lint/pull/176 got merged but I forgot about. 

After adding that flag, I can definitely see that the config seems to be ignored.

**Comment by trotzig** [comment]
I think it has to do with overcommit passing in different file paths (absolute?) than haml-lint uses when run in isolation. By changing the glob pattern in `haml-lint.yml` to this, both tools are doing the right thing (ignoring the file): 

```yml
linters:
  ConsecutiveComments:
    exclude:
      - '**/main.html.haml'
  LineLength:
    max: 110
```

Let me know if you are able to use this workaround!
