### ISSUE TITLE
CustomScript adding extra arguments

### ISSUE THREAD

**Issue by viamin** [brigade/overcommit#490]
I have a CustomScript to install yarn packages. I'm seeing a failure when running it because an extra 0 seems to appear in the arguments:

```
Running post-merge hooks
Run CustomScript.......................................[CustomScript] FAILED
yarn 0 v0.23.2
error Command "0" not found.
```

Here's the relevant section of my .overcommit.yml:
```
PostMerge:
  BundleInstall:
    enabled: true
  CustomScript:
    enabled: true
    required_executable: './bin/yarn'
```

bin/yarn is provided by the [webpacker](https://github.com/rails/webpacker) gem, and is simply calling yarnpkg:

```
VENDOR_PATH = File.expand_path('..', __dir__)
Dir.chdir(VENDOR_PATH) do
  begin
    exec "yarnpkg #{ARGV.join(" ")}"
  rescue Errno::ENOENT
    puts "Yarn executable was not detected in the system."
    puts "Download Yarn at https://yarnpkg.com/en/docs/install"
  end
end
```

Running $ ./bin/yarn in bash works, and runs the install command:
```
$ ./bin/yarn
yarn install v0.23.2
[1/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.96s.
```
