### ISSUE TITLE
Overcommit fails due to Rubocop config change, despite being set to 'warn'

### ISSUE THREAD

**Issue by brandondrew** [brigade/overcommit#511]
My overcommit config says to *warn* on Rubocop failures:

```
PreCommit:
  ALL:
    quiet: false
  RuboCop:
    enabled: true
    on_fail: warn
```

But Overcommit is making my commit fail because of a change in Rubocop's config key names:

```
Analyze with RuboCop........................................[RuboCop] FAILED
Unexpected output: unable to determine line number or type of error/warning for output:
(...)/.rubocop.yml - AllCops/Excludes was renamed to AllCops/Exclude
```
