### ISSUE TITLE
Support unversioned/local hooks

### ISSUE THREAD

**Issue by harto** [brigade/overcommit#527]
I was wondering if there's a generalized way to run hooks that are specific to my development environment. For example, I'd like a post-checkout hook that calls `ctags` with a specific configuration, but many engineers on my team don't use `ctags`.

One thought I had was to implement a hook that could be configured to look for unversioned hooks in a specified directory. I.e. maybe something like:
```
PostCheckout:
  Local:
    path: ".unversioned-git-hooks"
```

Then if `<repo>/.unversioned-git-hooks` contained `post-checkout`, etc. they would be run after regular Overcommit hooks. And `/.unversioned-git-hooks` could be added to `.gitignore`.

**Comment by harto** [comment]
Actually, maybe the above makes more sense as a kind of global configuration setting. But anyway, that's one idea. :)

**Comment by harto** [comment]
I figured out a way to do this.

I added a bunch of hook definitions like this:
```yaml
PostCheckout:
  Local:
    required_executable: ".git-hooks/local/post-checkout"

PostCommit:
  Local:
    required_executable: ".git-hooks/local/post-commit"
```

Then I check those files into version control. They look like e.g.:
```bash
#!/usr/bin/env bash
if [[ -f .local-git-hooks/post-checkout ]]; then
  exec .local-git-hooks/post-checkout $*
fi
```

Then, I can optionally create hooks in `.local-git-hooks`, which is added to `.gitignore`.
