### ISSUE TITLE
TrailingWhitespace does not get run automatically

### ISSUE THREAD

**Issue by rabcat** [brigade/overcommit#574]
config file:
```yaml
quiet: false

PreCommit:
  TrailingWhitespace:
    enabled: true
```

When I run git commit, vim pops up at once.
But with overcommit -r, I get

```
Running pre-commit hooks
Check for trailing whitespace....................[TrailingWhitespace] FAILED
Errors on modified lines:
/home/rabcat/Desktop/testProj/hello_world.cpp:6:    cout << "Hello World" << endl;                   

✗ One or more pre-commit hooks failed
```

Why is  TrailingWhitespace not run automatically upon git commit?

**Comment by rabcat** [comment]
Changed config file to
```
CommitMsg:
  RussianNovel:
    enabled: true

PreCommit:
  TrailingWhitespace:
    enabled: true
    quiet: false
```
Still does not work.
And I confirmed that I have done git add.
```
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   hello_world.cpp

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	--git-common-dir/
	.overcommit.yml
	hello_world
```
