### ISSUE TITLE
EsLint executed from terminal and overcommit give different results

### ISSUE THREAD

**Issue by Rob117** [brigade/overcommit#576]
EsLint executed from Terminal:

`./node_modules/.bin/eslint src __tests__  --ext .js`

Outputs 3 errors (intentional)

EsLint run with the following config produces an ignored/included file conflict (which makes sense, keep reading):

```
PreCommit:
  EsLint:
   enabled: true
   required_executable: './node_modules/.bin/eslint'
   command: ['./node_modules/.bin/eslint', 'src', '__tests__', '--ext', '.js']
   on_warn: fail
   include:
     - '.eslintrc.js'
```

Running `overcommit --run` gives me an error:
```
...(previous 3 errors)
Warnings on lines you didn't modify:
/Users/r-sherling/test_projects/navigation/.eslintrc.js: line 0, col 0, Warning - File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override.
```

Makes sense. Then I try to not include my .eslintrc.js file by removing the include section, and this happens:

```
M3C-2017mac04:navigation r-sherling$ overcommit --run
Running pre-commit hooks
Analyze with ESLint..........................................[EsLint] FAILED
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at /Users/r-sherling/test_projects/navigation/node_modules/eslint-plugin-flowtype/dist/rules/noDupeKeys.js:76:32
    at arrayEach (/Users/r-sherling/test_projects/navigation/node_modules/lodash/lodash.js:508:11)
    at Function.forEach (/Users/r-sherling/test_projects/navigation/node_modules/lodash/lodash.js:9334:14)
    at checkForDuplicates (/Users/r-sherling/test_projects/navigation/node_modules/eslint-plugin-flowtype/dist/rules/noDupeKeys.js:73:22)
    at listeners.(anonymous function).forEach.listener (/Users/r-sherling/test_projects/navigation/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/r-sherling/test_projects/navigation/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/r-sherling/test_projects/navigation/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/r-sherling/test_projects/navigation/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/r-sherling/test_projects/navigation/node_modules/eslint/lib/util/node-event-generator.js:294:14)


✗ One or more pre-commit hooks failed
```

I don't know how to include the file so it reads the rules and stops throwing type errors without it also saying I'm including ignored files. I don't want to lint .eslintrc.js, and adding '--config', '.eslintrc.js' to the command does nothing.

Any assistance would be appreciated.

**Comment by sds** [comment]
You shouldn't need to specify the `command` option explicitly. What was your goal in changing it?

By changing it, you'll now always list the `src` and `__tests__` directories in addition to any files you've modified. That's likely not what you want.

If you want to add command line flags to include in the command, use the `flags` option:

```yaml
PreCommit:
  ...
  flags: ['--ext', '.js'] # Just an example. I'm not sure what you're trying to do
```

I would suggest not specifying `command` or `include` and using the default configuration.
