### ISSUE TITLE
overcommit PreCommit hook not run?

### ISSUE THREAD

**Issue by zachwalton** [brigade/overcommit#581]
* I have run `overcommit --install`
* I have run `overcommit --sign`

What might I be doing wrong?

`.overcommit.yml`:

```
PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['bundle', 'exec', 'rubocop']
```

```
13:29 $ overcommit -l | grep RuboCop
  RuboCop: enabled
$ overcommit -r
Running pre-commit hooks
Analyze with RuboCop........................................[RuboCop] FAILED
Errors on modified lines:
/project/source.rb:123:55: C: Layout/SpaceInsideParens: Space inside parentheses detected. (https://github.com/bbatsov/ruby-style-guide#no-spaces-braces)


✗ One or more pre-commit hooks failed
$ git commit --allow-empty -m "a bogus commit message"
Running pre-commit hooks

✓ All pre-commit hooks passed
```
