### ISSUE TITLE
Hang with Minitest and RSpec PrePush hooks

### ISSUE THREAD

**Issue by HarlemSquirrel** [brigade/overcommit#586]
I have an app that has both Minitest tests and RSpec specs. I cannot run them in parallel since both test suites make changes to the same database. When trying to run one or more with `parallelize: false` the prepush hooks hang similar to #476 until I interrupt the process. 

```yaml
PrePush:
  Minitest:
    enabled: true

  RSpec:
    enabled: true
    parallelize: false
```

```
➤ git push
Updating signature for configuration file...
Running pre-push hooks
Run RSpec test suite..........................................[RSpec] OK
^C
➤
Interrupt signal received. Stopping hooks...

⚠  Hook run interrupted by user
```

Setting only Minitest to `parallelize: false` will show Minitest succeeding but then hangs. 

Setting both to `parallelize: false` will result in RSpec succeeding and then hang.

Also, I am using JRuby.

**Comment by HarlemSquirrel** [comment]
It seems that the test suite runs quite slowly on JRuby. It took over 14 minutes to run with four failure on JRuby 9.1.17.0

[jruby-9-1-17-0--rspec-output.txt](https://github.com/brigade/overcommit/files/2186103/jruby-9-1-17-0--rspec-output.txt)

**Comment by HarlemSquirrel** [comment]
I was able to work around this using a `RakeTarget` pre-push hook instead.

```yml
# .overcommit.yml

PrePush:
  RakeTarget:
    enabled: true
    env:
      RAILS_ENV: test
    targets:
      - spec
      - test
```
