### ISSUE TITLE
Stylelint running against all stylesheets

### ISSUE THREAD

**Issue by damonbauer** [brigade/overcommit#599]
Given the following overcommit config, `stylelint` is run across ALL `scss` files, rather than only those that were changed.

```yml
PreCommit:
  Stylelint:
    enabled: true
    command: ['npx', 'stylelint']
    flags: ['./app/assets/stylesheets/**/*.scss']
    include:
      - 'app/assets/stylesheets/**/*.scss'
    requires_files: true
```

I've also tried changing the `include` path to be `'./app/...`, as well as leaving off `include` and `requires_files` entirely, but the result is the same. It feels like [`applicable_files`](https://github.com/brigade/overcommit/blob/60f18f485c19e8ba5c578d984ef0caacf58eb966/lib/overcommit/hook/pre_commit/stylelint.rb#L12) doesn't seem to be respecting only unchanged files, but I'm not sure.

This is my first time using overcommit, so if I'm missing something, please let me know!
