### ISSUE TITLE
When running PrePush hooks, RuboCop says it passes but I suspect it never runs

### ISSUE THREAD

**Issue by gunterja** [brigade/overcommit#609]
Whenever overcommit runs my PrePush hooks, it always says rubocop passes even though I have purposefully introduced errors to test this. My EsLint config runs fine, which has me totally stumped. Any ideas what could be happening? 

Output from manual run of rubocop:
![image](https://user-images.githubusercontent.com/12376954/49760730-709bb200-fc82-11e8-8cd8-96280c37cfb7.png)

`.overcommit.yml`
```yml
verify_signatures: false
PrePush:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    required_executable: 'rubocop'
    command: ['bundle', 'exec', 'rubocop']
    # I included the following line to see if anything was being executed. No output visible
    # command: ['echo', '"test"']
    quiet: false
  EsLint:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['yarn', 'lint']
    quiet: false
```
