### ISSUE TITLE
Precommit ExecutePermissions no message output

### ISSUE THREAD

**Issue by WenbinHou** [brigade/overcommit#615]
I add `ExecutePermissions` in `PreCommit`, the hook did run but no "Check ..... [ExecutePermissions] OK" was printed.

My `.overcommit.yml`:
````
PreCommit:
  TrailingWhitespace:
    enabled: true

  LineEndings:
    enabled: true
    exclude:
      - develop/vssln/scattercc.sln
      - develop/vssln/*/*.vcxproj
      - develop/vssln/*/*.vcxproj.filters
      - develop/vssln/*/*.vcxitems
      - develop/vssln/*/*.vcxitems.filters
    eol: "\n"

  ExecutePermissions:
    enabled: true
````

The output is:
````
Running pre-commit hooks
Check for trailing whitespace....................[TrailingWhitespace] OK
Check line endings......................................[LineEndings] OK

✓ All pre-commit hooks passed
````

I can confirm the hook did work, and fails me if I accidently put executable permission on some file.
But where is the "Check xxx .............. [ExecutePermissions] OK" ?
