### ISSUE TITLE
Reek.yml is not correctly processed when run via overcommit

### ISSUE THREAD

**Issue by andreheijstek** [brigade/overcommit#622]
I'm having this problem when running reek via overcommit. I am using reek 5.3.1 and overcommit 0.46.0
The specific problem is that it ignores the exclude_path db, so I am getting lots of warnings on my migrations which I want to ignore.
Here's my .reek.yml

```
exclude_paths:
  - db
  - vendor
  - public
  - lib

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    FeatureEnvy:
      enabled: false
```

**Comment by sds** [comment]
Hey @andreheijstek, this looks very similar to https://github.com/troessner/reek/issues/1202, which was an issue with `reek`, not Overcommit. Perhaps the behavior of `reek` has changed or the `--force-exclusion` flag no longer works. Would appreciate you digging in or opening an issue on the `reek` project to confirm. Also, make sure you haven't overridden the `flags` option in your `.overcommit.yml`, as that can remove the `--force-exclusion` flag.


Hope that helps!

**Comment by mvz** [comment]
@sds what are the options overcommit passes to Reek?

**Comment by sds** [comment]
@mvz Depends what the user configures. Default is:
https://github.com/brigade/overcommit/blob/7f9c425cd7d7c05f0cb7dd8d05963ed935e2d4f2/config/default.yml#L632

**Comment by mvz** [comment]
Thanks, @sds!

**Comment by andreheijstek** [comment]
Here's my .overcommit.yml
```
CommitMsg:
  CapitalizedSubject:
    enabled: false

  EmptyMessage:
    enabled: false

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail

  AuthorEmail:
    enabled: true

  AuthorName:
    enabled: true

  MergeConflicts:
    enabled: true

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true

  Fasterer:
    enabled: true

  BundleAudit:
    enabled: true

  Reek:
    enabled: true

  RailsSchemaUpToDate:
    enabled: false

PrePush:
  Brakeman:
    enabled: true

```
